<a href="https://colab.research.google.com/github/umashankar43631/colab_notebooks/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
print(np.arange(1,15,2))

[ 1  3  5  7  9 11 13]


In [ ]:
print(np.ones((3,4)))
print(np.zeros((3,4)))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
print(10**1.5)

31.622776601683793


In [ ]:
np.logspace(1,3,5)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [ ]:
ar1 = np.array([1,2,3])
print(f"array dimension{ar1.ndim}, array shape {ar1.shape}")

array dimension1, array shape (3,)


In [ ]:
print(ar1.size)


3


In [ ]:
ar2 = np.array([[1,2,3], [4,5,6]])
print(ar2.shape)
print(ar2.size)
print(ar2)

(2, 3)
6
[[1 2 3]
 [4 5 6]]


In [ ]:
print("arr1 properties:")
print("ndim:", arr1.ndim)
print("shape:", arr1.shape)
print("size:", arr1.size)
print("dtype:", arr1.dtype)

print("\narr2 properties:")
print("ndim:", arr2.ndim)
print("shape:", arr2.shape)
print("size:", arr2.size)
print("dtype:", arr2.dtype)

arr1 properties:
ndim: 1
shape: (3,)
size: 3
dtype: int64

arr2 properties:
ndim: 2
shape: (2, 2)
size: 4
dtype: int64


**arrange and reshape**

**`np.arange(start, stop, step)`**: This function creates a NumPy array with evenly spaced values within a given interval.

*   `start`: The starting value of the sequence (inclusive).
*   `stop`: The end value of the sequence (exclusive).
*   `step`: The step size between values (default is 1).

For example, `np.arange(10)` creates an array from 0 to 9. `np.arange(2, 10, 2)` creates an array with values 2, 4, 6, and 8.

**`.reshape(shape)`**: This method changes the shape of a NumPy array without changing its data.

*   `shape`: A tuple or integer specifying the new dimensions of the array. The total number of elements in the original array must match the total number of elements in the new shape. You can use `-1` in one of the dimensions, and NumPy will automatically calculate the correct size for that dimension based on the array's size.

For example, if you have a 1D array with 12 elements, you can reshape it into a 2D array of shape `(3, 4)` or `(4, 3)`, or a 3D array of shape `(2, 3, 2)`, as long as the product of the dimensions equals 12.

In [ ]:
# 4x5 -> 2d matrix
# 2x2 -> 2d matrix

In [ ]:
3x4 -2d matrix
3x4

In [ ]:
np.arange(1,25,1).reshape((2,3,4))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
arr3d = np.arange(2 * 3 * 4).reshape((2, 3, 4))
print("3D Array (arr3d):\n", arr3d)

arr4d = np.arange(2 * 3 * 4 * 5).reshape((2, 3, 4, 5))
print("\n4D Array (arr4d):\n", arr4d)

print("\n slicing on arr3d:")
print("arr3d[1, :, [1, 3]]:\n", arr3d[1, :, [1, 3]])
print("arr3d[0, [0, 2], :]:\n", arr3d[0, [0, 2], :])

print("\nslicing on arr4d:")
print("arr4d[0, 1, :, [0, 4]]:\n", arr4d[0, 1, :, [0, 4]])
print("arr4d[:, 0, [1, 3], :]:\n", arr4d[:, 0, [1, 3], :])

3D Array (arr3d):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

4D Array (arr4d):
 [[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]

 slicing on arr3d:
arr3d[1, :, [1, 3]]:
 [[13 17 21]
 [15 19 23]]
arr3d[0, [0, 2], :]:
 [[ 0  1  2  3]
 [ 8  9 10 11]]

slicing on arr4d:
arr4d[0, 1, :, [0, 4]]:
 [[20 25 30 35]
 [24 29 34 39]]
arr4d[:, 0, [1, 3], :]:
 [[[ 5  6  7  8  9]
  [15 1

In [ ]:
print(arr3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
print("arr3d[1, :, [1, 3]]:\n", arr3d[1, :, [1, 3]])

arr3d[1, :, [1, 3]]:
 [[13 17 21]
 [15 19 23]]


In [ ]:
arr3d[:,:,2].flatten()

array([ 2,  6, 10, 14, 18, 22])

In [ ]:
# Zeros array
zeros_array = np.zeros((2, 3))
print("Zeros Array:\n", zeros_array)

# Ones array
ones_array = np.ones((2, 3))
print("\nOnes Array:\n", ones_array)

# Full array with constant value
full_array = np.full((2, 3), 7)
print("\nFull Array (filled with 7):\n", full_array)

# Identity matrix
eye_array = np.eye(3)
print("\nIdentity Matrix (Eye):\n", eye_array)

# Empty array (uninitialized values)
empty_array = np.empty((2, 3))
print("\nEmpty Array (uninitialized values):\n", empty_array)

In [ ]:
# Scalar Addition

arr = np.array([[1, 2], [3, 4]])
result = arr + 5
print(result)


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 2], [2, 2]])
print(a * b)

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a @ b)  # or np.matmul(a, b)


In [ ]:
np.linspace(1,3,3)

array([1., 2., 3.])